version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: qreports-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: relatorios
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - qreports-network

  backend:
    build: ./backend
    container_name: qreports-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: relatorios
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - qreports-network

  frontend:
    build: ./frontend
    container_name: qreports-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - qreports-network

volumes:
  mysql-data:


networks:
  qreports-network:
    driver: bridge
