version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: qreports-mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: qreports_auth
      MYSQL_ROOT_HOST: "%"
    secrets:
      - db_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - qreports-network
    healthcheck:
      # Garante MySQL pronto
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: qreports-backend
    ports:
      - "3000:3000"
    environment:
      AUTH_DB_HOST: mysql
      AUTH_DB_PORT: 3306
      AUTH_DB_USER: root
      AUTH_DB_NAME: qreports_auth
      AUTH_DB_PASSWORD_FILE: /run/secrets/db_password

      REPORT_DB_READ_USER: ${REPORT_DB_READ_USER}
      REPORT_DB_READ_PASSWORD_FILE: /run/secrets/report_db_read_password

      REPORT_DB_WRITE_USER: ${REPORT_DB_WRITE_USER}
      REPORT_DB_WRITE_PASSWORD_FILE: /run/secrets/report_db_write_password

      JWT_SECRET_FILE: /run/secrets/jwt_secret
      JWT_EXPIRES_IN: 8h

    secrets:
      - db_password
      - report_db_read_password
      - report_db_write_password
      - jwt_secret

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./shared:/shared
    networks:
      - qreports-network

  frontend:
    build: ./frontend
    container_name: qreports-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./shared:/shared
    depends_on:
      - backend
    networks:
      - qreports-network

volumes:
  mysql-data:


networks:
  qreports-network:
    driver: bridge

secrets:
  db_password:
    file: ./.secrets/db_password.txt
  report_db_read_password:
    file: ./.secrets/report_db_read_password.txt
  report_db_write_password:
    file: ./.secrets/report_db_write_password.txt
  jwt_secret:
    file: ./.secrets/jwt_secret.txt
